### ISSUE TITLE
what is the  difference between aok.js and json-server?

### ISSUE THREAD

**Issue by zhangweiHello** [apporoad/aok.js#4]
the two are so similar， what is the difference?

**Comment by apporoad** [comment]
感谢关注：
1. aok在json处理上面应该没有json-server那么多的功能，但是在性能方面更强大  
2. aok重视的是文件即资源概念，目的是让人急速开发api  
3. 扩展性也是aok的一个区别点把，aok后续不会添加特别多的功能，但可以用插件来实现这个扩展  
4. aok主要用于二次封装，算是一个中间件 
5. 总之json-server非常优秀，2个框架还是有所区别的

 
Thanks for your attention:
1. Aok should not have as much functionality in JSON processing as JSON-Server, but it is more powerful in terms of performance
2. Aok focuses on the file-as-resource concept, which is intended to enable rapid API development
3. Extensibility is also a special feature of AOK. Aok will not add too many features in the future, but it can be implemented by plug-ins
4. Aok is mainly used for secondary packaging and is considered as middleware
5. In a word, JSON-Server is very excellent, and the two frameworks are different

**Comment by apporoad** [comment]
还有一些区别点：
1. aok实现不仅仅是一个工具，它主要目的是轻量化我们的项目，去接口化，去web框架化，一个文件实现一个项目
2. 同时支持静态文件，所以可以将前端和后端放在一个项目里面，甚至前后端代码是同一份

There are also some differences:

1. Aok implementation is not just a tool, its main purpose is to lightweight our project, de-interface, de-web framework, one file to implement a project

2. Supports static files at the same time, so you can put the frontend and the backend in the one project, even if the front end and the back end are using the same codes

**Comment by zhangweiHello** [comment]
i see, i will try it
